// <auto-generated />
using System;
using GaragePro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GaragePro.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504001152_AddReactMockOperationalEndpoints")]
    partial class AddReactMockOperationalEndpoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GaragePro.Core.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Complement")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complement");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("number");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("street");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_addresses_client_id");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("GaragePro.Core.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpectedEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_end_at");

                    b.Property<bool>("IsRescheduled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rescheduled");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("ProductValueSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("product_value_snapshot");

                    b.Property<int>("RescheduleCount")
                        .HasColumnType("integer")
                        .HasColumnName("reschedule_count");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<decimal>("ServiceValueSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("service_value_snapshot");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_value");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_appointments");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_appointments_client_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_appointments_product_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_appointments_service_id");

                    b.HasIndex("StartAt")
                        .HasDatabaseName("ix_appointments_start_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_appointments_status");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_appointments_vehicle_id");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("GaragePro.Core.Entities.AppointmentRescheduleHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<DateTimeOffset>("NewExpectedEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_expected_end_at");

                    b.Property<DateTimeOffset>("NewStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_start_at");

                    b.Property<DateTimeOffset>("PreviousExpectedEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_expected_end_at");

                    b.Property<DateTimeOffset>("PreviousStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_start_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_appointment_reschedule_histories");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("ix_appointment_reschedule_histories_appointment_id");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("ix_appointment_reschedule_histories_changed_by_user_id");

                    b.ToTable("appointment_reschedule_histories", (string)null);
                });

            modelBuilder.Entity("GaragePro.Core.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address_text");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("document");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("standard")
                        .HasColumnName("tier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("Document")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_document");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("GaragePro.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("barcode");

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("category");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("MinStock")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("min_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Size")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("size");

                    b.Property<string>("Sku")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("sku");

                    b.Property<decimal>("Stock")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("stock");

                    b.Property<string>("Supplier")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("supplier");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("un")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_products_sku")
                        .HasFilter("sku IS NOT NULL");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_cost", "cost >= 0");

                            t.HasCheckConstraint("ck_products_min_stock", "min_stock >= 0");

                            t.HasCheckConstraint("ck_products_price", "price >= 0");

                            t.HasCheckConstraint("ck_products_stock", "stock >= 0");
                        });
                });

            modelBuilder.Entity("GaragePro.Core.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Duration")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("duration");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("standard")
                        .HasColumnName("tier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_services_code")
                        .HasFilter("code IS NOT NULL");

                    b.ToTable("services", null, t =>
                        {
                            t.HasCheckConstraint("ck_services_cost", "cost >= 0");

                            t.HasCheckConstraint("ck_services_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("GaragePro.Core.Entities.ServiceMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("pk_service_materials");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_service_materials_product_id");

                    b.HasIndex("ServiceId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_service_materials_service_id_product_id");

                    b.ToTable("service_materials", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_materials_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("GaragePro.Core.Entities.ServiceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BoxNumber")
                        .HasColumnType("integer")
                        .HasColumnName("box_number");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("order_number");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_service_orders");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_service_orders_client_id");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_service_orders_order_number");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("ix_service_orders_scheduled_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_service_orders_status");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_service_orders_vehicle_id");

                    b.ToTable("service_orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_orders_box_number", "box_number between 1 and 6");

                            t.HasCheckConstraint("ck_service_orders_total_price", "total_price >= 0");
                        });
                });

            modelBuilder.Entity("GaragePro.Core.Entities.ServiceOrderProductLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_total");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_service_order_product_lines");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_service_order_product_lines_product_id");

                    b.HasIndex("ServiceOrderId")
                        .HasDatabaseName("ix_service_order_product_lines_service_order_id");

                    b.ToTable("service_order_product_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_order_product_lines_line_total", "line_total >= 0");

                            t.HasCheckConstraint("ck_service_order_product_lines_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_service_order_product_lines_unit_price", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("GaragePro.Core.Entities.ServiceOrderServiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_total");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service_name");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_service_order_service_lines");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_order_service_lines_service_id");

                    b.HasIndex("ServiceOrderId")
                        .HasDatabaseName("ix_service_order_service_lines_service_order_id");

                    b.ToTable("service_order_service_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_order_service_lines_line_total", "line_total >= 0");

                            t.HasCheckConstraint("ck_service_order_service_lines_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_service_order_service_lines_unit_price", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("GaragePro.Core.Entities.ServiceStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("pk_service_steps");

                    b.HasIndex("ServiceId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_service_steps_service_id_position");

                    b.ToTable("service_steps", (string)null);
                });

            modelBuilder.Entity("GaragePro.Core.Entities.ServiceVehiclePrice", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("vehicle_type");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.HasKey("ServiceId", "VehicleType")
                        .HasName("pk_service_vehicle_prices");

                    b.ToTable("service_vehicle_prices", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_vehicle_prices_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("GaragePro.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string[]>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("roles");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GaragePro.Core.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_plate");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Car")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VIN")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("vin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_vehicles_client_id");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_license_plate");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("GaragePro.Core.Entities.VehicleTransferRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FromClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_client_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ToClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_client_id");

                    b.Property<DateTimeOffset>("TransferredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transferred_at");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_transfer_records");

                    b.HasIndex("FromClientId")
                        .HasDatabaseName("ix_vehicle_transfer_records_from_client_id");

                    b.HasIndex("ToClientId")
                        .HasDatabaseName("ix_vehicle_transfer_records_to_client_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_vehicle_transfer_records_vehicle_id");

                    b.ToTable("vehicle_transfer_records", (string)null);
                });

            modelBuilder.Entity("GaragePro.Core.Entities.Address", b =>
                {
                    b.HasOne("GaragePro.Core.Entities.Client", null)
                        .WithMany("Addresses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_clients_client_id");
                });

            modelBuilder.Entity("GaragePro.Core.Entities.Appointment", b =>
                {
                    b.HasOne("GaragePro.Core.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_clients_client_id");

                    b.HasOne("GaragePro.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_products_product_id");

                    b.HasOne("GaragePro.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_services_service_id");

                    b.HasOne("GaragePro.Core.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_vehicles_vehicle_id");

                    b.Navigation("Client");

                    b.Navigation("Product");

                    b.Navigation("Service");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GaragePro.Core.Entities.AppointmentRescheduleHistory", b =>
                {
                    b.HasOne("GaragePro.Core.Entities.Appointment", "Appointment")
                        .WithMany("RescheduleHistory")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointment_reschedule_histories_appointments_appointment_id");

                    b.HasOne("GaragePro.Core.Entities.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointment_reschedule_histories_users_changed_by_user_id");

                    b.Navigation("Appointment");

                    b.Navigation("ChangedBy");
                });

            modelBuilder.Entity("GaragePro.Core.Entities.ServiceMaterial", b =>
                {
                    b.HasOne("GaragePro.Core.Entities.Product", "Product")
                        .WithMany("ServiceMaterials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_materials_products_product_id");

                    b.HasOne("GaragePro.Core.Entities.Service", "Service")
                        .WithMany("Materials")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_materials_services_service_id");

                    b.Navigation("Product");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GaragePro.Core.Entities.ServiceOrder", b =>
                {
                    b.HasOne("GaragePro.Core.Entities.Client", "Client")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_orders_clients_client_id");

                    b.HasOne("GaragePro.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_orders_vehicles_vehicle_id");

                    b.Navigation("Client");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GaragePro.Core.Entities.ServiceOrderProductLine", b =>
                {
                    b.HasOne("GaragePro.Core.Entities.Product", "Product")
                        .WithMany("ServiceOrderProductLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_order_product_lines_products_product_id");

                    b.HasOne("GaragePro.Core.Entities.ServiceOrder", "ServiceOrder")
                        .WithMany("ProductLines")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_order_product_lines_service_orders_service_order_id");

                    b.Navigation("Product");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("GaragePro.Core.Entities.ServiceOrderServiceLine", b =>
                {
                    b.HasOne("GaragePro.Core.Entities.Service", "Service")
                        .WithMany("ServiceOrderServiceLines")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_order_service_lines_services_service_id");

                    b.HasOne("GaragePro.Core.Entities.ServiceOrder", "ServiceOrder")
                        .WithMany("ServiceLines")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_order_service_lines_service_orders_service_order_id");

                    b.Navigation("Service");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("GaragePro.Core.Entities.ServiceStep", b =>
                {
                    b.HasOne("GaragePro.Core.Entities.Service", "Service")
                        .WithMany("Steps")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_steps_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GaragePro.Core.Entities.ServiceVehiclePrice", b =>
                {
                    b.HasOne("GaragePro.Core.Entities.Service", "Service")
                        .WithMany("VehiclePrices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_vehicle_prices_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GaragePro.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("GaragePro.Core.Entities.Client", "Client")
                        .WithMany("Vehicles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_clients_client_id");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GaragePro.Core.Entities.VehicleTransferRecord", b =>
                {
                    b.HasOne("GaragePro.Core.Entities.Client", "FromClient")
                        .WithMany()
                        .HasForeignKey("FromClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_transfer_records_clients_from_client_id");

                    b.HasOne("GaragePro.Core.Entities.Client", "ToClient")
                        .WithMany()
                        .HasForeignKey("ToClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_transfer_records_clients_to_client_id");

                    b.HasOne("GaragePro.Core.Entities.Vehicle", null)
                        .WithMany("TransferHistory")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_transfer_records_vehicles_vehicle_id");

                    b.Navigation("FromClient");

                    b.Navigation("ToClient");
                });

            modelBuilder.Entity("GaragePro.Core.Entities.Appointment", b =>
                {
                    b.Navigation("RescheduleHistory");
                });

            modelBuilder.Entity("GaragePro.Core.Entities.Client", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ServiceOrders");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("GaragePro.Core.Entities.Product", b =>
                {
                    b.Navigation("ServiceMaterials");

                    b.Navigation("ServiceOrderProductLines");
                });

            modelBuilder.Entity("GaragePro.Core.Entities.Service", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("ServiceOrderServiceLines");

                    b.Navigation("Steps");

                    b.Navigation("VehiclePrices");
                });

            modelBuilder.Entity("GaragePro.Core.Entities.ServiceOrder", b =>
                {
                    b.Navigation("ProductLines");

                    b.Navigation("ServiceLines");
                });

            modelBuilder.Entity("GaragePro.Core.Entities.Vehicle", b =>
                {
                    b.Navigation("ServiceOrders");

                    b.Navigation("TransferHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
